name: versify
description: Versify

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  font_awesome_flutter: ^8.8.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  firebase_auth: ^0.20.0+1
  google_sign_in: ^4.4.4
  cloud_firestore: ^0.16.0
  firebase_storage: ^7.0.0
  firebase_core: ^0.7.0-nullsafety.1
  provider: ^4.0.0
  flutter_spinkit: "^4.0.0"
  pull_to_refresh: ^2.0.0
  scroll_bottom_navigation_bar: ^3.0.0
  shared_preferences: ^0.5.12+4
  vibration: ^1.7.3
  skeleton_loader: ^1.0.2+2
  draggable_scrollbar: ^0.0.4
  url_launcher: ^5.7.10
  phone_number: ^0.8.1+1
  intl_phone_number_input: ^0.6.0
  http: ^0.12.0+2
  xml: ^4.5.1
  cached_network_image: ^2.5.1
  flutter_icons: ^1.1.0
  flutter_cache_manager:
  firebase_dynamic_links: ^0.7.0+1
  esys_flutter_share: ^1.0.2
  google_fonts: ^1.1.2
  flutter_launcher_icons: ^0.8.1

    

  
  
  



dev_dependencies:
  flutter_test:
    sdk: flutter
  

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/versify_logo_v2.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  assets:
   - assets/images/
 

  fonts:
    - family: Nunito
      fonts:
        - asset: fonts\Nunito-Black.ttf
        - asset: fonts\Nunito-BlackItalic.ttf
        - asset: fonts\Nunito-Bold.ttf
        - asset: fonts\Nunito-BoldItalic.ttf
        - asset: fonts\Nunito-ExtraBold.ttf
        - asset: fonts\Nunito-ExtraBoldItalic.ttf
        - asset: fonts\Nunito-ExtraLight.ttf
        - asset: fonts\Nunito-ExtraLightItalic.ttf
        - asset: fonts\Nunito-Italic.ttf
        - asset: fonts\Nunito-Light.ttf
        - asset: fonts\Nunito-LightItalic.ttf
        - asset: fonts\Nunito-Regular.ttf
        - asset: fonts\Nunito-SemiBold.ttf
        - asset: fonts\Nunito-SemiBoldItalic.ttf

    - family: Ubuntu
      fonts:
        - asset: fonts\Ubuntu-Regular.ttf

    - family: Itim
      fonts:
        - asset: fonts\Itim-Regular.ttf

    - family: Libre
      fonts:
        - asset: fonts\LibreBaskerville-Bold.ttf
        - asset: fonts\LibreBaskerville-Italic.ttf
        - asset: fonts\LibreBaskerville-Regular.ttf

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
