name: versify
description: Versify

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  font_awesome_flutter: ^8.8.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons:
  flutter_icons:
  flutter_launcher_icons: 
  flutter_spinkit: 
  google_fonts:
  google_sign_in: ^5.0.3
  firebase_auth: ^1.2.0
  cloud_firestore: ^2.2.0
  firebase_storage: ^8.1.0
  firebase_core: ^1.2.0
  firebase_dynamic_links: ^2.0.4
  firebase_messaging: ^10.0.0
  provider: ^5.0.0
  pull_to_refresh: ^2.0.0 
  shared_preferences: ^2.0.5
  vibration: ^1.7.3
  url_launcher: ^6.0.4
  intl_phone_number_input: ^0.7.0+2
  http: ^0.13.3
  xml: ^5.1.0
  cached_network_image: ^3.0.0
  share: ^2.0.1
  overlay_tutorial: ^2.0.1
  shimmer_animation: ^2.0.0
  overlay_support: ^1.2.1
  image_picker: ^0.8.0+3
  webview_flutter: ^2.0.12
  scrollable_positioned_list: ^0.1.10
  ansicolor: ^2.0.1
  # lint: ^1.5.3
  # esys_flutter_share: ^1.0.2
  # scroll_bottom_navigation_bar: 
  # skeleton_loader: 
  # draggable_scrollbar: 
  # phone_number: ^0.10.0
  # flutter_cache_manager:



dev_dependencies:
  flutter_test:
    sdk: flutter
  

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/purple_square_v1.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec`

# The following section is specific to Flutter.
flutter:

  assets:
   - assets/images/
   - assets/images/backgrounds/
 

  fonts:
    - family: Nunito
      fonts:
        - asset: fonts\Nunito-Black.ttf
        - asset: fonts\Nunito-BlackItalic.ttf
        - asset: fonts\Nunito-Bold.ttf
        - asset: fonts\Nunito-BoldItalic.ttf
        - asset: fonts\Nunito-ExtraBold.ttf
        - asset: fonts\Nunito-ExtraBoldItalic.ttf
        - asset: fonts\Nunito-ExtraLight.ttf
        - asset: fonts\Nunito-ExtraLightItalic.ttf
        - asset: fonts\Nunito-Italic.ttf
        - asset: fonts\Nunito-Light.ttf
        - asset: fonts\Nunito-LightItalic.ttf
        - asset: fonts\Nunito-Regular.ttf
        - asset: fonts\Nunito-SemiBold.ttf
        - asset: fonts\Nunito-SemiBoldItalic.ttf

    - family: Ubuntu
      fonts:
        - asset: fonts\Ubuntu-Regular.ttf

    - family: Itim
      fonts:
        - asset: fonts\Itim-Regular.ttf

    - family: Libre
      fonts:
        - asset: fonts\LibreBaskerville-Bold.ttf
        - asset: fonts\LibreBaskerville-Italic.ttf
        - asset: fonts\LibreBaskerville-Regular.ttf

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
